/**
 * Weather conditions of the old Yahoo! weather feed (`_tt` in `jquery.zweatherfeed.js`) in all languages of vis-2.
 *
 * The weather widget gets its condition texts from any adapter, in any language. If a text is exactly one of these
 * conditions in one of the languages, it is shown in the language of the widget; any other text is shown as it is.
 *
 * vis-1 also accepted a condition that merely CONTAINED the text, which turned "Rain" into "Mixed rain and snow" and
 * an empty text into "Tornado". That second pass is gone.
 */
import { toLang, type Lang } from './words';

type Condition = Record<Lang, string>;

const CONDITIONS: Condition[] = [
    {
        en: 'Tornado',
        de: 'Tornado',
        ru: 'Торнадо',
        pt: 'Tornado',
        nl: 'Tornado',
        fr: 'Tornade',
        it: 'Tornado',
        es: 'Tornado',
        pl: 'Tornado',
        uk: 'Торнадо',
        'zh-cn': '龙卷风',
    },
    {
        en: 'Tropical storm',
        de: 'Tropischer Sturm',
        ru: 'Тропический шторм',
        pt: 'Tempestade tropical',
        nl: 'Tropische storm',
        fr: 'Tempête tropicale',
        it: 'Tempesta tropicale',
        es: 'Tormenta tropical',
        pl: 'Burza tropikalna',
        uk: 'Тропічний шторм',
        'zh-cn': '热带风暴',
    },
    {
        en: 'Hurricane',
        de: 'Hurrikan',
        ru: 'Ураган',
        pt: 'Furacão',
        nl: 'Orkaan',
        fr: 'Ouragan',
        it: 'Uragano',
        es: 'Huracán',
        pl: 'Huragan',
        uk: 'Ураган',
        'zh-cn': '飓风',
    },
    {
        en: 'Severe thunderstorms',
        de: 'Starke Gewitter',
        ru: 'Сильные грозы',
        pt: 'Trovoadas fortes',
        nl: 'Zware onweersbuien',
        fr: 'Orages violents',
        it: 'Forti temporali',
        es: 'Tormentas fuertes',
        pl: 'Silne burze',
        uk: 'Сильні грози',
        'zh-cn': '强雷暴',
    },
    {
        en: 'Thunderstorms',
        de: 'Gewitter',
        ru: 'Грозы',
        pt: 'Trovoadas',
        nl: 'Onweersbuien',
        fr: 'Orages',
        it: 'Temporali',
        es: 'Tormentas',
        pl: 'Burze',
        uk: 'Грози',
        'zh-cn': '雷暴',
    },
    {
        en: 'Mixed rain and snow',
        de: 'Regen mit Schnee',
        ru: 'Дождь со снегом',
        pt: 'Chuva e neve',
        nl: 'Regen en sneeuw',
        fr: 'Pluie et neige',
        it: 'Pioggia mista a neve',
        es: 'Lluvia y nieve',
        pl: 'Deszcz ze śniegiem',
        uk: 'Дощ зі снігом',
        'zh-cn': '雨夹雪',
    },
    {
        en: 'Mixed rain and sleet',
        de: 'Regen mit Graupel',
        ru: 'Дождь с мокрым снегом',
        pt: 'Chuva e granizo miúdo',
        nl: 'Regen en ijzel',
        fr: 'Pluie et grésil',
        it: 'Pioggia mista a nevischio',
        es: 'Lluvia y aguanieve',
        pl: 'Deszcz z krupą lodową',
        uk: 'Дощ з мокрим снігом',
        'zh-cn': '雨夹冰粒',
    },
    {
        en: 'Mixed snow and sleet',
        de: 'Schnee mit Graupel',
        ru: 'Снег с градом',
        pt: 'Neve e granizo miúdo',
        nl: 'Sneeuw en ijzel',
        fr: 'Neige et grésil',
        it: 'Neve mista a nevischio',
        es: 'Nieve y aguanieve',
        pl: 'Śnieg z krupą lodową',
        uk: 'Сніг з крупою',
        'zh-cn': '雪夹冰粒',
    },
    {
        en: 'Freezing drizzle',
        de: 'Eisnieselregen',
        ru: 'Изморозь',
        pt: 'Chuvisco gelado',
        nl: 'Aanvriezende motregen',
        fr: 'Bruine verglaçante',
        it: 'Pioviggine gelata',
        es: 'Llovizna helada',
        pl: 'Marznąca mżawka',
        uk: 'Крижана мряка',
        'zh-cn': '冻毛毛雨',
    },
    {
        en: 'Drizzle',
        de: 'Nieselregen',
        ru: 'Моросящий дождь',
        pt: 'Chuvisco',
        nl: 'Motregen',
        fr: 'Bruine',
        it: 'Pioviggine',
        es: 'Llovizna',
        pl: 'Mżawka',
        uk: 'Мряка',
        'zh-cn': '毛毛雨',
    },
    {
        en: 'Freezing rain',
        de: 'Eisregen',
        ru: 'Ледяной дождь',
        pt: 'Chuva gelada',
        nl: 'Aanvriezende regen',
        fr: 'Pluie verglaçante',
        it: 'Pioggia gelata',
        es: 'Lluvia helada',
        pl: 'Marznący deszcz',
        uk: 'Крижаний дощ',
        'zh-cn': '冻雨',
    },
    {
        en: 'Showers',
        de: 'Regenschauer',
        ru: 'Ливень',
        pt: 'Aguaceiros',
        nl: 'Buien',
        fr: 'Averses',
        it: 'Rovesci',
        es: 'Chubascos',
        pl: 'Przelotne opady',
        uk: 'Злива',
        'zh-cn': '阵雨',
    },
    {
        en: 'Snow flurries',
        de: 'Schneetreiben',
        ru: 'Снегопад',
        pt: 'Neve fraca',
        nl: 'Sneeuwvlagen',
        fr: 'Flocons de neige',
        it: 'Neve leggera',
        es: 'Copos de nieve',
        pl: 'Przelotny śnieg',
        uk: 'Снігопад',
        'zh-cn': '飘雪',
    },
    {
        en: 'Light snow showers',
        de: 'Leichter Schneeregen',
        ru: 'Небольшой дождь со снегом',
        pt: 'Aguaceiros de neve fracos',
        nl: 'Lichte sneeuwbuien',
        fr: 'Faibles averses de neige',
        it: 'Deboli rovesci di neve',
        es: 'Chubascos de nieve ligeros',
        pl: 'Słabe przelotne opady śniegu',
        uk: 'Невеликий снігопад',
        'zh-cn': '小阵雪',
    },
    {
        en: 'Blowing snow',
        de: 'Schneeböen',
        ru: 'Метель',
        pt: 'Neve com vento',
        nl: 'Stuifsneeuw',
        fr: 'Chasse-neige',
        it: 'Neve portata dal vento',
        es: 'Ventisca',
        pl: 'Zamieć',
        uk: 'Хуртовина',
        'zh-cn': '风吹雪',
    },
    {
        en: 'Snow',
        de: 'Schnee',
        ru: 'Снег',
        pt: 'Neve',
        nl: 'Sneeuw',
        fr: 'Neige',
        it: 'Neve',
        es: 'Nieve',
        pl: 'Śnieg',
        uk: 'Сніг',
        'zh-cn': '雪',
    },
    {
        en: 'Hail',
        de: 'Hagel',
        ru: 'Град',
        pt: 'Granizo',
        nl: 'Hagel',
        fr: 'Grêle',
        it: 'Grandine',
        es: 'Granizo',
        pl: 'Grad',
        uk: 'Град',
        'zh-cn': '冰雹',
    },
    {
        en: 'Sleet',
        de: 'Graupel',
        ru: 'Мелкий град',
        pt: 'Granizo miúdo',
        nl: 'IJzel',
        fr: 'Grésil',
        it: 'Nevischio',
        es: 'Aguanieve',
        pl: 'Krupa lodowa',
        uk: 'Крупа',
        'zh-cn': '冰粒',
    },
    {
        en: 'Dust',
        de: 'Diesig',
        ru: 'Пыльно',
        pt: 'Poeira',
        nl: 'Stof',
        fr: 'Poussière',
        it: 'Polvere',
        es: 'Polvo',
        pl: 'Pył',
        uk: 'Пил',
        'zh-cn': '浮尘',
    },
    {
        en: 'Foggy',
        de: 'Neblig',
        ru: 'Туманно',
        pt: 'Nevoeiro',
        nl: 'Mistig',
        fr: 'Brouillard',
        it: 'Nebbia',
        es: 'Niebla',
        pl: 'Mgła',
        uk: 'Туман',
        'zh-cn': '雾',
    },
    {
        en: 'Haze',
        de: 'Dunst',
        ru: 'Дымка',
        pt: 'Neblina',
        nl: 'Nevel',
        fr: 'Brume',
        it: 'Foschia',
        es: 'Calima',
        pl: 'Zamglenie',
        uk: 'Серпанок',
        'zh-cn': '霾',
    },
    {
        en: 'Smoky',
        de: 'Qualmig',
        ru: 'Задымление',
        pt: 'Fumo',
        nl: 'Rokerig',
        fr: 'Fumée',
        it: 'Fumo',
        es: 'Humo',
        pl: 'Zadymienie',
        uk: 'Задимлення',
        'zh-cn': '烟雾',
    },
    {
        en: 'Blustery',
        de: 'Stürmisch',
        ru: 'Порывистый ветер',
        pt: 'Rajadas de vento',
        nl: 'Stormachtig',
        fr: 'Rafales',
        it: 'Raffiche di vento',
        es: 'Rachas de viento',
        pl: 'Porywisty wiatr',
        uk: 'Поривчастий вітер',
        'zh-cn': '阵风',
    },
    {
        en: 'Windy',
        de: 'Windig',
        ru: 'Ветрено',
        pt: 'Ventoso',
        nl: 'Winderig',
        fr: 'Venteux',
        it: 'Ventoso',
        es: 'Ventoso',
        pl: 'Wietrznie',
        uk: 'Вітряно',
        'zh-cn': '有风',
    },
    {
        en: 'Cold',
        de: 'Kalt',
        ru: 'Холодно',
        pt: 'Frio',
        nl: 'Koud',
        fr: 'Froid',
        it: 'Freddo',
        es: 'Frío',
        pl: 'Zimno',
        uk: 'Холодно',
        'zh-cn': '寒冷',
    },
    {
        en: 'Cloudy',
        de: 'Wolkig',
        ru: 'Облачно',
        pt: 'Nublado',
        nl: 'Bewolkt',
        fr: 'Nuageux',
        it: 'Nuvoloso',
        es: 'Nublado',
        pl: 'Pochmurno',
        uk: 'Хмарно',
        'zh-cn': '多云',
    },
    {
        en: 'Mostly cloudy (night)',
        de: 'Überwiegend wolkig (Nacht)',
        ru: 'В основном облачно (ночь)',
        pt: 'Muito nublado (noite)',
        nl: 'Overwegend bewolkt (nacht)',
        fr: 'Plutôt nuageux (nuit)',
        it: 'Prevalentemente nuvoloso (notte)',
        es: 'Mayormente nublado (noche)',
        pl: 'Przeważnie pochmurno (noc)',
        uk: 'Переважно хмарно (ніч)',
        'zh-cn': '大部多云（夜间）',
    },
    {
        en: 'Mostly cloudy (day)',
        de: 'Überwiegend wolkig (Tag)',
        ru: 'В основном облачно (день)',
        pt: 'Muito nublado (dia)',
        nl: 'Overwegend bewolkt (dag)',
        fr: 'Plutôt nuageux (jour)',
        it: 'Prevalentemente nuvoloso (giorno)',
        es: 'Mayormente nublado (día)',
        pl: 'Przeważnie pochmurno (dzień)',
        uk: 'Переважно хмарно (день)',
        'zh-cn': '大部多云（白天）',
    },
    {
        en: 'Partly cloudy (night)',
        de: 'Teilweise wolkig (Nacht)',
        ru: 'Местами облачно',
        pt: 'Parcialmente nublado (noite)',
        nl: 'Half bewolkt (nacht)',
        fr: 'Partiellement nuageux (nuit)',
        it: 'Parzialmente nuvoloso (notte)',
        es: 'Parcialmente nublado (noche)',
        pl: 'Częściowe zachmurzenie (noc)',
        uk: 'Мінлива хмарність (ніч)',
        'zh-cn': '局部多云（夜间）',
    },
    {
        en: 'Partly cloudy (day)',
        de: 'Teilweise wolkig (Tag)',
        ru: 'Преимущественно солнечно',
        pt: 'Parcialmente nublado (dia)',
        nl: 'Half bewolkt (dag)',
        fr: 'Partiellement nuageux (jour)',
        it: 'Parzialmente nuvoloso (giorno)',
        es: 'Parcialmente nublado (día)',
        pl: 'Częściowe zachmurzenie (dzień)',
        uk: 'Мінлива хмарність (день)',
        'zh-cn': '局部多云（白天）',
    },
    {
        en: 'Clear (night)',
        de: 'Klare Nacht',
        ru: 'Ясно',
        pt: 'Céu limpo (noite)',
        nl: 'Helder (nacht)',
        fr: 'Dégagé (nuit)',
        it: 'Sereno (notte)',
        es: 'Despejado (noche)',
        pl: 'Bezchmurnie (noc)',
        uk: 'Ясно (ніч)',
        'zh-cn': '晴朗（夜间）',
    },
    {
        en: 'Sunny',
        de: 'Sonnig',
        ru: 'Солнечно',
        pt: 'Ensolarado',
        nl: 'Zonnig',
        fr: 'Ensoleillé',
        it: 'Soleggiato',
        es: 'Soleado',
        pl: 'Słonecznie',
        uk: 'Сонячно',
        'zh-cn': '晴',
    },
    {
        en: 'Fair (night)',
        de: 'Schönwetter (Nacht)',
        ru: 'Прекрасная погода (ночь)',
        pt: 'Bom tempo (noite)',
        nl: 'Mooi weer (nacht)',
        fr: 'Beau temps (nuit)',
        it: 'Bel tempo (notte)',
        es: 'Buen tiempo (noche)',
        pl: 'Ładna pogoda (noc)',
        uk: 'Гарна погода (ніч)',
        'zh-cn': '晴好（夜间）',
    },
    {
        en: 'Fair (day)',
        de: 'Schönwetter (Tag)',
        ru: 'Прекрасная погода (день)',
        pt: 'Bom tempo (dia)',
        nl: 'Mooi weer (dag)',
        fr: 'Beau temps (jour)',
        it: 'Bel tempo (giorno)',
        es: 'Buen tiempo (día)',
        pl: 'Ładna pogoda (dzień)',
        uk: 'Гарна погода (день)',
        'zh-cn': '晴好（白天）',
    },
    {
        en: 'Mixed rain and hail',
        de: 'Regen mit Hagel',
        ru: 'Дождь с градом',
        pt: 'Chuva e granizo',
        nl: 'Regen en hagel',
        fr: 'Pluie et grêle',
        it: 'Pioggia e grandine',
        es: 'Lluvia y granizo',
        pl: 'Deszcz z gradem',
        uk: 'Дощ з градом',
        'zh-cn': '雨夹冰雹',
    },
    {
        en: 'Hot',
        de: 'Heiß',
        ru: 'Жарко',
        pt: 'Calor',
        nl: 'Heet',
        fr: 'Chaud',
        it: 'Caldo',
        es: 'Caluroso',
        pl: 'Upał',
        uk: 'Спекотно',
        'zh-cn': '炎热',
    },
    {
        en: 'Isolated thunderstorms',
        de: 'Gebietsweise Gewitter',
        ru: 'Одиночные грозы',
        pt: 'Trovoadas isoladas',
        nl: 'Plaatselijk onweer',
        fr: 'Orages isolés',
        it: 'Temporali isolati',
        es: 'Tormentas aisladas',
        pl: 'Miejscami burze',
        uk: 'Поодинокі грози',
        'zh-cn': '局部雷暴',
    },
    {
        en: 'Scattered thunderstorms',
        de: 'Vereinzelte Gewitter',
        ru: 'Рассеянные грозы',
        pt: 'Trovoadas dispersas',
        nl: 'Verspreide onweersbuien',
        fr: 'Orages épars',
        it: 'Temporali sparsi',
        es: 'Tormentas dispersas',
        pl: 'Przelotne burze',
        uk: 'Розсіяні грози',
        'zh-cn': '零星雷暴',
    },
    {
        en: 'Scattered showers',
        de: 'Vereinzelter Regen',
        ru: 'Местами дождь',
        pt: 'Aguaceiros dispersos',
        nl: 'Verspreide buien',
        fr: 'Averses éparses',
        it: 'Rovesci sparsi',
        es: 'Chubascos dispersos',
        pl: 'Przelotne opady deszczu',
        uk: 'Місцями дощ',
        'zh-cn': '零星阵雨',
    },
    {
        en: 'Heavy snow',
        de: 'Starker Schneefall',
        ru: 'Сильный снегопад',
        pt: 'Neve forte',
        nl: 'Zware sneeuwval',
        fr: 'Fortes chutes de neige',
        it: 'Forti nevicate',
        es: 'Nevada intensa',
        pl: 'Intensywne opady śniegu',
        uk: 'Сильний снігопад',
        'zh-cn': '大雪',
    },
    {
        en: 'Scattered snow showers',
        de: 'Vereinzelter Schneeregen',
        ru: 'Местами снег',
        pt: 'Aguaceiros de neve dispersos',
        nl: 'Verspreide sneeuwbuien',
        fr: 'Averses de neige éparses',
        it: 'Rovesci di neve sparsi',
        es: 'Chubascos de nieve dispersos',
        pl: 'Miejscami przelotne opady śniegu',
        uk: 'Місцями сніг',
        'zh-cn': '零星阵雪',
    },
    {
        en: 'Partly cloudy',
        de: 'Teilweise wolkig',
        ru: 'Переменная облачность',
        pt: 'Parcialmente nublado',
        nl: 'Half bewolkt',
        fr: 'Partiellement nuageux',
        it: 'Parzialmente nuvoloso',
        es: 'Parcialmente nublado',
        pl: 'Częściowe zachmurzenie',
        uk: 'Мінлива хмарність',
        'zh-cn': '局部多云',
    },
    {
        en: 'Thundershowers',
        de: 'Gewitterschauer',
        ru: 'Грозовые ливни',
        pt: 'Aguaceiros com trovoada',
        nl: 'Buien met onweer',
        fr: 'Averses orageuses',
        it: 'Rovesci temporaleschi',
        es: 'Chubascos tormentosos',
        pl: 'Przelotne opady z burzą',
        uk: 'Грозові зливи',
        'zh-cn': '雷阵雨',
    },
    {
        en: 'Snow showers',
        de: 'Schneeregen',
        ru: 'Снег с дождем',
        pt: 'Aguaceiros de neve',
        nl: 'Sneeuwbuien',
        fr: 'Averses de neige',
        it: 'Rovesci di neve',
        es: 'Chubascos de nieve',
        pl: 'Przelotne opady śniegu',
        uk: 'Снігопади',
        'zh-cn': '阵雪',
    },
    {
        en: 'Isolated thundershowers',
        de: 'Gebietsweise Gewitterschauer',
        ru: 'Местами грозы',
        pt: 'Aguaceiros com trovoada isolados',
        nl: 'Plaatselijk buien met onweer',
        fr: 'Averses orageuses isolées',
        it: 'Rovesci temporaleschi isolati',
        es: 'Chubascos tormentosos aislados',
        pl: 'Miejscami przelotne opady z burzą',
        uk: 'Місцями грозові зливи',
        'zh-cn': '局部雷阵雨',
    },
];

/**
 * Plain conditions that were not in the Yahoo! list but are what most weather adapters deliver. They come after
 * the Yahoo! ones, so a text that is both keeps its Yahoo! translation.
 */
CONDITIONS.push(
    {
        en: 'Rain',
        de: 'Regen',
        ru: 'Дождь',
        pt: 'Chuva',
        nl: 'Regen',
        fr: 'Pluie',
        it: 'Pioggia',
        es: 'Lluvia',
        pl: 'Deszcz',
        uk: 'Дощ',
        'zh-cn': '雨',
    },
    {
        en: 'Light rain',
        de: 'Leichter Regen',
        ru: 'Небольшой дождь',
        pt: 'Chuva fraca',
        nl: 'Lichte regen',
        fr: 'Pluie faible',
        it: 'Pioggia leggera',
        es: 'Lluvia ligera',
        pl: 'Słaby deszcz',
        uk: 'Невеликий дощ',
        'zh-cn': '小雨',
    },
    {
        en: 'Heavy rain',
        de: 'Starker Regen',
        ru: 'Сильный дождь',
        pt: 'Chuva forte',
        nl: 'Zware regen',
        fr: 'Forte pluie',
        it: 'Pioggia forte',
        es: 'Lluvia fuerte',
        pl: 'Silny deszcz',
        uk: 'Сильний дощ',
        'zh-cn': '大雨',
    },
    {
        en: 'Clear',
        de: 'Klar',
        ru: 'Ясно',
        pt: 'Céu limpo',
        nl: 'Helder',
        fr: 'Dégagé',
        it: 'Sereno',
        es: 'Despejado',
        pl: 'Bezchmurnie',
        uk: 'Ясно',
        'zh-cn': '晴朗',
    },
    {
        en: 'Overcast',
        de: 'Bedeckt',
        ru: 'Пасмурно',
        pt: 'Encoberto',
        nl: 'Betrokken',
        fr: 'Couvert',
        it: 'Coperto',
        es: 'Cubierto',
        pl: 'Całkowite zachmurzenie',
        uk: 'Похмуро',
        'zh-cn': '阴',
    },
    {
        en: 'Mostly cloudy',
        de: 'Überwiegend bewölkt',
        ru: 'Облачно с прояснениями',
        pt: 'Muito nublado',
        nl: 'Overwegend bewolkt',
        fr: 'Plutôt nuageux',
        it: 'Prevalentemente nuvoloso',
        es: 'Mayormente nublado',
        pl: 'Przeważnie pochmurno',
        uk: 'Хмарно з проясненнями',
        'zh-cn': '大部多云',
    },
    {
        en: 'Mostly sunny',
        de: 'Überwiegend sonnig',
        ru: 'Преимущественно ясно',
        pt: 'Predominantemente ensolarado',
        nl: 'Overwegend zonnig',
        fr: 'Plutôt ensoleillé',
        it: 'Prevalentemente soleggiato',
        es: 'Mayormente soleado',
        pl: 'Przeważnie słonecznie',
        uk: 'Переважно сонячно',
        'zh-cn': '大部晴朗',
    },
    {
        en: 'Fog',
        de: 'Nebel',
        ru: 'Туман',
        pt: 'Nevoeiro',
        nl: 'Mist',
        fr: 'Brouillard',
        it: 'Nebbia',
        es: 'Niebla',
        pl: 'Mgła',
        uk: 'Туман',
        'zh-cn': '雾',
    },
    {
        en: 'Thunderstorm',
        de: 'Gewitter',
        ru: 'Гроза',
        pt: 'Trovoada',
        nl: 'Onweer',
        fr: 'Orage',
        it: 'Temporale',
        es: 'Tormenta',
        pl: 'Burza',
        uk: 'Гроза',
        'zh-cn': '雷暴',
    },
);

/** Every spelling of every condition, lower case, pointing to its condition */
const LOOKUP = new Map<string, Condition>();
for (const condition of CONDITIONS) {
    for (const text of Object.values(condition)) {
        const key = text.toLowerCase();
        // the first condition wins, as with the search of vis-1
        if (!LOOKUP.has(key)) {
            LOOKUP.set(key, condition);
        }
    }
}
// spellings of vis-1 that are no longer used for the output, but may still come from an adapter or a script
const ALIASES: Record<string, string> = {
    'bowing snow': 'Blowing snow',
    ветрянно: 'Windy',
    'приемущественно солнечно': 'Partly cloudy (day)',
    'торнадо - сиди дома!': 'Tornado',
    'в основном облачно': 'Mostly cloudy (night)',
    'прекрасная погода': 'Fair (night)',
};
for (const [alias, en] of Object.entries(ALIASES)) {
    const condition = CONDITIONS.find(c => c.en === en);
    if (condition && !LOOKUP.has(alias)) {
        LOOKUP.set(alias, condition);
    }
}

/** The condition text in the given language, or the text unchanged if it is not one of the known conditions */
export function translateCondition(text: string, lang: string): string {
    const condition = text ? LOOKUP.get(text.trim().toLowerCase()) : undefined;
    return condition ? condition[toLang(lang)] : text;
}
