version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '7 2 19 * *'
    open-pull-requests-limit: 20
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: npm
    directory: '/src-widgets'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '7 2 19 * *'
    open-pull-requests-limit: 20
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: Europe/Berlin
      cronjob: '7 2 19 * *'
    open-pull-requests-limit: 20
